boffer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from main.views import HomeView

urlpatterns = [
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^accounts/', include('user.urls', namespace='user')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^auction/', include("auction.urls")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v0/', include('api_v0.urls', namespace='api_v0')),
]

user/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^auction/$', AuctionListView.as_view(), name='auction_list'),
    url(r'^items/$', ItemListView.as_view(), name='item_list'),
    url(r'^news/$', NewsView.as_view(), name='news'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'main/home.html'

main/templates/main/home.html
{% extends "tmpl.html" %}


{% load staticfiles %}


{% block content %}
	<div class="block_one">
		<div class="main-wrapper">
			<div class="header">
				<a href="{% url "home" %}" class="logo"><img src="{% static "images/logo.svg" %}" alt="logo"></a>
				<div class="header-registration">
{% if request.user.is_authenticated %}
                    <a href="{% url "user:auction_list" %}">{{ request.user.get_display_name }}</a>
{% else %}
					<a href="{% url "account_login" %}">Вход</a>
					<a href="{% url "account_signup" %}">Регистрация</a>
{% endif %}
					<div class="clear"></div>
				</div>
			</div>
			<div class="h1">Сервис для покупателей автозапчастей <br>
			Работает по системе аукциона</div>
			<div class="container">
				<div class="column">
					<img src="{% static "images/gear-icon.png" %}">
					<span>Вы находите необходимую для вас деталь</span>
				</div>
				<div class="column">
					<img src="{% static "images/time-icon.png" %}">
					<span>Создаете аукцион и ждете выгодного предложения</span>
				</div>
				<div class="column">
					<img src="{% static "images/money-icon.png" %}">
					<span>Преобретаете деталь по самой выгодной цене</span>
				</div>
			</div>
			<a href="#" class="button create-auction">Создать аукцион</a>
		</div>
	</div>
	<div class="block_two">
		<div class="main-wrapper">
			<div class="h1">Что вы получите от использования системы boffer?</div>
			<div class="video-present">
				<a href="#"></a>
				<div class="h2">посмотреть видеопрезентацию</div>
			</div>
			<div class="container">
				<div class="column">
					<img src="{% static "images/engine-icon.png" %}">
					<span>Быстрый и удобный доступ к каталогу автозапчастей</span>
				</div>
				<div class="column">
					<img src="{% static "images/wallet-icon.png" %}">
					<span>Максимально выгодные покупки от системы аукциона</span>
				</div>
				<div class="column">
					<img src="{% static "images/star-icon.png" %}">
					<span>Вы можете быть уверены в качестве предостовляемых товаров</span>
				</div>
				<div class="column">
					<img src="{% static "images/user-icon.png" %}">
					<span>Вы сможете доверить работу менеджеру или заняться этим самому</span>
				</div>
				<div class="column">
					<img src="{% static "images/comments-icon.png" %}">
					<span>Отзывы о нашей работе</span>
				</div>
				<div class="column">
					<img src="{% static "images/alert-icon.png" %}">
					<span>Мгновенные уведомления о намерении купить ваш товар</span>
				</div>
			</div>
		</div>
	</div>
	<div class="block_three">
		<div class="main-wrapper">
			<a href="index.php" class="logo"><img src="{% static "images/logo.svg" %}" alt="logo"></a>
			<span>Boffer - это сервис, позволяющий поставщикам автозапчастей находить клиентов, а покупателям выбрать автозапчасть по самой выгодной цене</span>
			<div class="container">
				<div class="column">
					<span class="top">18 855</span>
					<span class="bottom">продавцов в системе</span>
				</div>
				<div class="column">
					<span class="top">1 360 535₽</span>
					<span class="bottom">общая сумма продаж</span>
				</div>
				<div class="column">
					<span class="top">335 456₽</span>
					<span class="bottom">сэкономлено</span>
				</div>
			</div>
			<a href="{% url "account_signup" %}" class="button registration">Регистрация</a>
		</div>
	</div>
	<div class="block_four">
		<div class="main-wrapper">
			<div class="h1">Завершенные аукционы</div>
			<ul class="slider">
				<li>
					<div class="column">
						<div class="diagramma">
							<span class="top">31%</span>
							<span class="bottom">сэкономлено</span>
							<!-- <canvas id="one-diag" class="circle" height="151" width="151"></canvas> -->
						</div>
						<a href="#" class="top">Двигатель 2.5 Toyota 2AR-FE Camry</a>
						<div class="middle">
							<span class="left">Авто:</span>
							<span class="right">TOYOTA CAMRY VIII</span>
						</div>
						<div class="bottom">
							<span class="left">Начальная цена:</span>
							<span class="right">80000₽</span>
						</div>
					</div>
					<div class="column">
						<div class="diagramma">
							<span class="top">25%</span>
							<span class="bottom">сэкономлено</span>
							<!-- <canvas id="two-diag" class="circle" height="151" width="151"></canvas> -->
						</div>
						<a href="#" class="top">Двигатель 2.5 Toyota 2AR-FE Camry</a>
						<div class="middle">
							<span class="left">Авто:</span>
							<span class="right">TOYOTA CAMRY VIII</span>
						</div>
						<div class="bottom">
							<span class="left">Начальная цена:</span>
							<span class="right">80000₽</span>
						</div>
					</div>
					<div class="column">
						<div class="diagramma">
							<span class="top">75%</span>
							<span class="bottom">сэкономлено</span>
							<!-- <canvas id="three-diag" class="circle" height="151" width="151"></canvas> -->
						</div>
						<a href="#" class="top">Двигатель 2.5 Toyota 2AR-FE Camry</a>
						<div class="middle">
							<span class="left">Авто:</span>
							<span class="right">TOYOTA CAMRY VIII</span>
						</div>
						<div class="bottom">
							<span class="left">Начальная цена:</span>
							<span class="right">80000₽</span>
						</div>
					</div>
					<div class="column">
						<div class="diagramma">
							<span class="top">90%</span>
							<span class="bottom">сэкономлено</span>
							<!-- <canvas id="four-diag" class="circle" height="151" width="151"></canvas> -->
						</div>
						<a href="#" class="top">Двигатель 2.5 Toyota 2AR-FE Camry</a>
						<div class="middle">
							<span class="left">Авто:</span>
							<span class="right">TOYOTA CAMRY VIII</span>
						</div>
						<div class="bottom">
							<span class="left">Начальная цена:</span>
							<span class="right">80000₽</span>
						</div>
					</div>
				</li>
				<li>
					<div class="column">
						<div class="diagramma">
							<span class="top">31%</span>
							<span class="bottom">сэкономлено</span>
							<!-- <canvas id="one-diag" class="circle" height="151" width="151"></canvas> -->
						</div>
						<a href="#" class="top">Двигатель 2.5 Toyota 2AR-FE Camry</a>
						<div class="middle">
							<span class="left">Авто:</span>
							<span class="right">TOYOTA CAMRY VIII</span>
						</div>
						<div class="bottom">
							<span class="left">Начальная цена:</span>
							<span class="right">80000₽</span>
						</div>
					</div>
					<div class="column">
						<div class="diagramma">
							<span class="top">31%</span>
							<span class="bottom">сэкономлено</span>
							<!-- <canvas id="two-diag" class="circle" height="151" width="151"></canvas> -->
						</div>
						<a href="#" class="top">Двигатель 2.5 Toyota 2AR-FE Camry</a>
						<div class="middle">
							<span class="left">Авто:</span>
							<span class="right">TOYOTA CAMRY VIII</span>
						</div>
						<div class="bottom">
							<span class="left">Начальная цена:</span>
							<span class="right">80000₽</span>
						</div>
					</div>
					<div class="column">
						<div class="diagramma">
							<span class="top">31%</span>
							<span class="bottom">сэкономлено</span>
							<!-- <canvas id="three-diag" class="circle" height="151" width="151"></canvas> -->
						</div>
						<a href="#" class="top">Двигатель 2.5 Toyota 2AR-FE Camry</a>
						<div class="middle">
							<span class="left">Авто:</span>
							<span class="right">TOYOTA CAMRY VIII</span>
						</div>
						<div class="bottom">
							<span class="left">Начальная цена:</span>
							<span class="right">80000₽</span>
						</div>
					</div>
					<div class="column">
						<div class="diagramma">
							<span class="top">31%</span>
							<span class="bottom">сэкономлено</span>
							<!-- <canvas id="four-diag" class="circle" height="151" width="151"></canvas> -->
						</div>
						<a href="#" class="top">Двигатель 2.5 Toyota 2AR-FE Camry</a>
						<div class="middle">
							<span class="left">Авто:</span>
							<span class="right">TOYOTA CAMRY VIII</span>
						</div>
						<div class="bottom">
							<span class="left">Начальная цена:</span>
							<span class="right">80000₽</span>
						</div>
					</div>
				</li>
			</ul>
		</div>
	</div>
	<div class="block_five">
		<div class="main-wrapper">
			<div class="left">
				<div class="h1">Boffer у вас в кармане</div>
				<div class="h2">Мобильное приложение Boffer</div>
				<ul>
					<li>Аукцион в реальном времени</li>
					<li>Интуитивный поиск автозапчастей</li>
					<li>Абсолютно бесплатно</li>
				</ul>
				<div class="social-button">
					<a href="#">
						<img src="{% static "images/app-store-button.png" %}">
					</a>
					<a href="#">
						<img src="{% static "images/google-market-button.png" %}">
					</a>
				</div>
			</div>
			<img src="{% static "images/iphone-6-silver.png" %}" class="banner">
			<div class="clear"></div>
		</div>
	</div>
	<div class="block_six">
		<div class="h1">Партнерам</div>
		<span>Boffer - это сервис, позволяющий поставщикам автозапчастей находить клиентов, а покупателям выбрать автозапчасть по самой выгодной цене</span>
		<a href="#" class="button partner">Стать партнером</a>
	</div>
{% endblock %}